integration-test: fix TestMultipleCloseCallback
This is the smallest change I have to fix this test. The callback is
not being called on Close(), test fails with:

--- FAIL: TestMultipleCloseCallback (2.02s)
    integration_test.go:133: Close() == 1, expected 0
    integration_test.go:137: Wrong number of calls to callback, got [0 0 0], expected [0 0 1]

Signed-off-by: Victor Toso <victortoso@redhat.com>